import daily_vol
full_fo = ['ACC','ADANIENT','ADANIPORTS','ADANIPOWER','AMARAJABAT','AMBUJACEM','APOLLOHOSP','APOLLOTYRE','ASHOKLEY','ASIANPAINT','AUROPHARMA','AXISBANK','BAJAJ-AUTO','BAJAJFINSV','BAJFINANCE','BALKRISIND','BANKBARODA','BATAINDIA','BEL','BERGEPAINT','BHARATFORG','BHARTIARTL','BHEL','BIOCON','BOSCHLTD','BPCL','BRITANNIA','CADILAHC','CANBK','CASTROLIND','CENTURYTEX','CESC','CHOLAFIN','CIPLA','COALINDIA','COLPAL','CONCOR','CUMMINSIND','DABUR','DISHTV','DIVISLAB','DLF','DRREDDY','EICHERMOT','EQUITAS','ESCORTS','EXIDEIND','FEDERALBNK','GAIL','GLENMARK','GMRINFRA','GODREJCP','GRASIM','HAVELLS','HCLTECH','HDFC','HDFCBANK','HEROMOTOCO','HINDALCO','HINDPETRO','HINDUNILVR','IBULHSGFIN','ICICIBANK','ICICIPRULI','IDEA','IDFCFIRSTB','IGL','INDIGO','INDUSINDBK','INFRATEL','INFY','IOC','ITC','JINDALSTEL','JSWSTEEL','JUBLFOOD','JUSTDIAL','KOTAKBANK','L&TFH','LICHSGFIN','LT','LUPIN','M&M','M&MFIN','MANAPPURAM','MARICO','MARUTI','MCDOWELL-N','MFSL','MGL','MINDTREE','MOTHERSUMI','MRF','MUTHOOTFIN','NATIONALUM','NBCC','NCC','NESTLEIND','NIITTECH','NMDC','NTPC','OIL','ONGC','PAGEIND','PEL','PETRONET','PFC','PIDILITIND','PNB','POWERGRID','PVR','RAMCOCEM','RBLBANK','RECLTD','RELIANCE','SAIL','SBIN','SHREECEM','SIEMENS','SRF','SRTRANSFIN','SUNPHARMA','SUNTV','TATACHEM','TATAMOTORS','TATAMTRDVR','TATAPOWER','TATASTEEL','TCS','TECHM','TITAN','TORNTPHARM','TORNTPOWER','TVSMOTOR','UBL','UJJIVAN','ULTRACEMCO','UPL','VEDL','VOLTAS','WIPRO','YESBANK','ZEEL']

#13.08.20
only_1d = ['AMBUJACEM', 'CADILAHC', 'CASTROLIND', 'CENTURYTEX', 'COALINDIA', 'CONCOR', 'DLF', 'HAVELLS', 'HINDALCO', 'HINDPETRO', 'ICICIBANK', 'JINDALSTEL', 'LT', 'MANAPPURAM', 'MARICO', 'MCDOWELL-N', 'SBILIFE', 'SRTRANSFIN', 'TATACHEM', 'UBL', 'VEDL', 'VOLTAS', 'WIPRO']
only_2d = ['AMARAJABAT', 'APOLLOTYRE', 'BEL', 'BERGEPAINT', 'BHARATFORG', 'CHOLAFIN', 'CUMMINSIND', 'GRASIM', 'HCLTECH', 'INFRATEL', 'M&MFIN', 'PETRONET', 'POWERGRID', 'RECLTD', 'SUNTV', 'TATAMOTORS', 'TECHM', 'TVSMOTOR', 'UJJIVAN', 'UPL']
only_3d = ['ADANIENT', 'ADANIPORTS', 'CESC', 'GODREJCP', 'JSWSTEEL', 'LICHSGFIN', 'MGL', 'MOTHERSUMI', 'RAMCOCEM', 'ZEEL']




date = '13_08 '




daily_vol.get_file()
daily_vol.fo(only_3d,(date)+ str(3))
daily_vol.fo(only_2d,(date)+ str(2))
daily_vol.fo(only_1d,(date)+ str(1))
daily_vol.fo(full_fo,(date)+ 'all ')

